### ISSUE TITLE
Idea / Suggestion: small border ...

### ISSUE THREAD

**Issue by moebiussurfing** [cmdwtf/imgui_toggle#1]
Hello, thanks for sharing this widget,

I just wanted to share my custom widget I did, 
adding a small border looks pretty cool too:

![image](https://user-images.githubusercontent.com/2106149/200734995-fbcab4d8-e682-4cb7-a0ee-b41a9738160f.png)

Here's my code if want to look into.
I think that theme colors are handled well too.
https://github.com/moebiussurfing/ofxSurfingImGui/blob/3933c930cc478359ac853103fbce55abebe49cdb/src/ImGui/widgets/ButtonsToggles.h#L690

Regards

**Comment by nitz** [comment]
Oh that looks fantastic! I will absolutely look at folding this in, it looks especially good with those knobs that are closer to the background color too.

**Comment by nitz** [comment]
Thank you very much for the inspiration! I added a flag, `ImGuiToggleFlags_Bordered` that enables border drawing similar to yours!
