### ISSUE TITLE
imgui combo box style 

### ISSUE THREAD

**Issue by chris0306** [cmdwtf/imgui_toggle#12]
![combobox](https://github.com/user-attachments/assets/eb22d795-f85a-47eb-877c-f64b54898e4e)
how to change combo box style like this

thanks!

**Comment by nitz** [comment]
Hey @chris0306, I think you've got the wrong project. This project is specifically for a [toggle](https://github.com/cmdwtf/imgui_toggle/raw/main/.meta/imgui_toggle_example.gif) control. You probably want the [Dear ImGui](https://github.com/ocornut/imgui) project proper.
